esurvey/config/routes.rb
Esurvey::Application.routes.draw do
  resources :messages

  get "notifications/index"

  resources :merit_templates

  resources :interviews do
    collection do
     get 'get_survey_question'
     get 'get_servey_conducter'
     get 'get_survey_result'
     get 'get_survey_town'
     post 'calculate_survey_result'
     get 'calculate_survey_result_of_town'
    end
  end

  resources :survey_results

  resources :surveys do 
    collection do
      get 'listsurveyor'
      get 'add_surveyors'
      post 'update_surveyor'
    end
  end

  resources :political_parties  do 
   resources :users 
 end

match 'service/get_assigned_surveys/:user_id' => 'service#get_assigned_surveys'
match '/service/get_merit_list_of_survey/:surveys_id/:merit_template_id' =>'service#get_merit_list_of_survey'
match '/service/get_assigned_village_for_survey/:survey_id/:user_id'=>'service#get_assigned_village_for_survey'
match '/service/get_assigned_question_for_survey/:survey_id'=>'service#get_assigned_question_for_survey'
match '/service/get_interview_info/:interview_id'=>'service#get_interview_info' 

root :to => 'home#login_form'
 

   match ':controller(/:action(/:id))(.:format)'
end

esurvey/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :political_party
  attr_accessible :authentication_token, :email, :encrypted_password, :first_name, :is_active, :last_name, :mobile_number, :reset_password_code, :reset_password_code_until, :salt,
  :password,:password_confirmation,:political_party_id,:role_id,:picture_attributes

   EMAIL_REGEX = /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i
 # validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :first_name, :presence => true
  validates :mobile_number,:presence=> true, :uniqueness =>{:scope =>[:political_party_id]}
  validates :email,:uniqueness =>{:scope =>[:political_party_id]},:format=> { with:  /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i,
    message: "only allows valid email address" },:allow_nil=>true,:allow_blank=> true
  validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20, :on => :create
  belongs_to  :role
  attr_accessor :password
  before_save :encrypt_password
  after_save :clear_password
  
  scope :active, lambda { |party_name| where("is_active= true and political_party_id=?",party_name) }
  scope :inactive, lambda { |party_name| where("is_active= false and political_party_id=?", party_name ) }

  belongs_to :political_parties
  
  has_many :interviews
  
  has_one :picture, :as => :imageable
  accepts_nested_attributes_for :picture

  has_many :servey_conducters

  def self.authenticate(username_or_email="", login_password="")

    if  EMAIL_REGEX.match(username_or_email)    
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_mobile_number(username_or_email)
    end

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end   

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end



  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

 def role_symbols
    ([role] || []).map {|r| r.title.underscore.to_sym}
 end


end

esurvey/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  filter_access_to :all
  before_filter :find_political_party


  def find_political_party
   @political_party = PoliticalParty.find(params[:political_party_id])
  end

  def index
    #@users = @political_party.users.all
    @active_users = User.active(@political_party.id)
    @inactive_users = User.inactive(@political_party.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = @political_party.users.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @user.build_picture
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = @political_party.users.find(params[:id])
    @user.build_picture if @user.picture.nil?
  end

  # POST /users
  # POST /users.json
  def create
   @user = @political_party.users.new(params[:user])
    @user.build_picture if @user.picture.nil?
    respond_to do |format|
      if @user.save
        format.html { redirect_to [@political_party, @user], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = @political_party.users.find(params[:id])
     @user.build_picture if @user.picture.nil?
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to [@political_party, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = @political_party.users.find(params[:id])
    #@user.destroy
    @user.update_attributes(:is_active=> !@user.is_active)
    respond_to do |format|
      format.html { redirect_to  [@political_party, @user]}
      format.json { head :no_content }
    end
  end
end

esurvey/app/helpers/users_helper.rb
module UsersHelper
end

esurvey/app/views/users/_form.html.erb
<%= form_for([@political_party, @user], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mobile_number, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :mobile_number, class: "form-control" %>
    </div>
  </div>
  
  <% if @user.new_record? %>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
   
  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <% end %>


 

  <div class="form-group">
    <%= f.label :role, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :role_id,Role.all.map{|r| [r.title.camelize,r.id]},{ :prompt=>"Select Role"}, class: "form-control" %>
    </div>
  </div>

<%= f.fields_for :picture do |picture| %>
<div class="form-group">
  <label class="col-sm-2 control-label" for="filebutton">Upload New Profile Image</label>
  <div class="col-sm-3">
      <%= picture.file_field :picture %>
     </div>
</div>
<% end %>


 <%  unless @user.new_record? %>

  <% unless @user.picture.nil? %>
  <div class="form-group">
  <label class="col-sm-2 control-label" for="filebutton">Exiting Profile Image</label>
     <div class="col-sm-3">
      <%= image_tag @user.picture.picture.url(:thumb)   %>
     </div>
   </div>  
   <% end %>
   <% end %>
 
 
 <%  unless @user.new_record? %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Update" ,class: "btn btn-primary" %>
    </div>
  </div>
 <% else %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create" ,class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% end %>

esurvey/app/views/users/edit.html.erb
<div class="page-header">
  <%= link_to political_party_users_url(@political_party), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to political_party_user_url(@political_party,@user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
 <h3 class="text-info"><u><b>Editing user</b></u></h3>
</div>

<%= render 'form' %>

esurvey/app/views/users/index.html.erb
<div class="page-header">
  <%= link_to new_political_party_user_path(@political_party), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New User
  <% end %>
  <h3 class="text-danger text-center "><u><b><%= @political_party.name  %>Membership </u></b></h3>
<h3 class="text-info"><u><b>Listing users</u></b></h3>
</div>



<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>  <th>S.No</th>
             <th>Profile Image</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Mobile number</th>
            <th>Position</th>
            <!-- <th>Is active</th> -->
           <!--  <th>Political party</th> -->
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
       <% @active_users.each_with_index do |user,index| %>
         <tr>
      
           <td><%= index+1 %></td>
            <td><%= image_tag user.picture.picture.url(:thumb),:class=>"img-responsive" ,:size=>"50x36" unless user.picture.nil?  %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.mobile_number %></td>
            <td><%= user.role.title.camelize %></td>
            <!-- <td><%= user.is_active %></td> -->
          <!--   <td><%= user.political_party.name %></td> -->
            <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe,political_party_user_path(@political_party,user),:class=>"btn btn-sm btn-info" %></td>
            <td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_political_party_user_path(@political_party,user),:class=>"btn btn-sm btn-success" %></td>
            <td><%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, political_party_user_url(@political_party,user),{ method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-sm btn-danger" } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>


<hr>
<h3 class="text-info"><u><b>Listing InActive users</u></b></h3>


<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>  <th>S.No</th>
             <th>Profile Image</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th>Mobile number</th>
            <th>Position</th>
            <!-- <th>Is active</th> -->
           <!--  <th>Political party</th> -->
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
       <% @inactive_users.each_with_index do |user,index| %>
         <tr>
      
           <td><%= index+1 %></td>
            <td><%= image_tag user.picture.picture.url(:thumb) unless user.picture.nil?  %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.mobile_number %></td>
              <td><%= user.role.title.camelize %></td>
            <!-- <td><%= user.is_active %></td> -->
            <!-- <td><%= user.political_party.name %></td> -->
            <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe,political_party_user_path(@political_party,user),:class=>"btn btn-sm btn-info" %></td>
            <td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_political_party_user_path(@political_party,user),:class=>"btn btn-sm btn-success" %></td>
            <td><%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, political_party_user_url(@political_party,user),{ method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-sm btn-danger" } %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

esurvey/app/views/users/new.html.erb
<div class="page-header">
  <%= link_to political_party_users_url(@political_party), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
 <h3 class="text-info"><u><b>New user</b></u></h3>
</div>

<%= render 'form' %>

esurvey/app/views/users/show.html.erb
<div class="page-header">
  <%= link_to political_party_users_url(@political_party), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_political_party_user_url(@political_party,@user), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show user</h1>
</div>

<dl class="dl-horizontal">
  <dt>First name:</dt>
  <dd><%= @user.first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @user.last_name %></dd>

  <dt>Email:</dt>
  <dd><%= @user.email %></dd>

  <dt>Mobile number:</dt>
  <dd><%= @user.mobile_number %></dd>
   
  <dt>Political party:</dt>
  <dd><%= @user.political_party.name %></dd>
  
  <dt>Is active:</dt>
  <dd><%= @user.is_active %></dd>

  

</dl>