esurvey/config/routes.rb
Esurvey::Application.routes.draw do
  resources :messages

  get "notifications/index"

  resources :merit_templates

  resources :interviews do
    collection do
     get 'get_survey_question'
     get 'get_servey_conducter'
     get 'get_survey_result'
     get 'get_survey_town'
     post 'calculate_survey_result'
     get 'calculate_survey_result_of_town'
    end
  end

  resources :survey_results

  resources :surveys do 
    collection do
      get 'listsurveyor'
      get 'add_surveyors'
      post 'update_surveyor'
    end
  end

  resources :political_parties  do 
   resources :users 
 end

match 'service/get_assigned_surveys/:user_id' => 'service#get_assigned_surveys'
match '/service/get_merit_list_of_survey/:surveys_id/:merit_template_id' =>'service#get_merit_list_of_survey'
match '/service/get_assigned_village_for_survey/:survey_id/:user_id'=>'service#get_assigned_village_for_survey'
match '/service/get_assigned_question_for_survey/:survey_id'=>'service#get_assigned_question_for_survey'
match '/service/get_interview_info/:interview_id'=>'service#get_interview_info' 

root :to => 'home#login_form'
 

   match ':controller(/:action(/:id))(.:format)'
end

esurvey/app/models/merit_template.rb
class MeritTemplate < ActiveRecord::Base
  attr_accessible :template_name, :merit_template_subjects_attributes
  validates :template_name,:presence=>true
  has_many :merit_template_subjects
  accepts_nested_attributes_for :merit_template_subjects
  has_many :surveys
end

esurvey/app/controllers/merit_templates_controller.rb
class MeritTemplatesController < ApplicationController
  # GET /merit_templates
  # GET /merit_templates.json
  filter_access_to :all
  def index
    @merit_templates = MeritTemplate.all(:include=>[:merit_template_subjects])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @merit_templates }
    end
  end

  # GET /merit_templates/1
  # GET /merit_templates/1.json
  def show
    @merit_template = MeritTemplate.find(params[:id],:include=>[:merit_template_subjects])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @merit_template }
    end
  end

  # GET /merit_templates/new
  # GET /merit_templates/new.json
  def new
    @merit_template = MeritTemplate.new
    3.times do
      @merit_template.merit_template_subjects.build
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @merit_template }
    end
  end

  # GET /merit_templates/1/edit
  def edit
    @merit_template = MeritTemplate.find(params[:id])
  end

  # POST /merit_templates
  # POST /merit_templates.json
  def create
    @merit_template = MeritTemplate.new(params[:merit_template])

    respond_to do |format|
      if @merit_template.save
        format.html { redirect_to @merit_template, notice: 'Merit template was successfully created.' }
        format.json { render json: @merit_template, status: :created, location: @merit_template }
      else
        format.html { render action: "new" }
        format.json { render json: @merit_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /merit_templates/1
  # PUT /merit_templates/1.json
  def update
    @merit_template = MeritTemplate.find(params[:id])

    respond_to do |format|
      if @merit_template.update_attributes(params[:merit_template])
        format.html { redirect_to @merit_template, notice: 'Merit template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @merit_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merit_templates/1
  # DELETE /merit_templates/1.json
  def destroy
    @merit_template = MeritTemplate.find(params[:id])
    @merit_template.destroy

    respond_to do |format|
      format.html { redirect_to merit_templates_url }
      format.json { head :no_content }
    end
  end
end

esurvey/app/helpers/merit_templates_helper.rb
module MeritTemplatesHelper
end

esurvey/app/views/merit_templates/_form.html.erb
<%= form_for(@merit_template, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @merit_template.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@merit_template.errors.count, "error") %> prohibited this merit_template from being saved:</h4>

      <ul>
      <% @merit_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :template_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :template_name, class: "form-control" %>
    </div>
  </div>

  <h3 class="text-danger text-left"><u><b>Subjects/Options</u></b></h3>
  <div class="form-group">
   <table class="table table-bordered dynamic">
  <thead>
    <tr class="bg-info">
     <th>Subject Name </th>
    <th>Subject Marks</th>
    <th>--</th>
  </tr>
  </thead>
   <tbody>
     <% @index=0 %>
     <%= f.fields_for :merit_template_subjects do |builder| %>

     <tr>
      
    <%= render 'merit_template_subject_fields', :f => builder,:index=>@index %>
   
    </tr>
    
  <% end %>
  </tbody>
  </table>
  <p class="btn btn-default"><%= link_to_add_fields "<span class='glyphicon glyphicon-plus'></span>".html_safe, f, 
:merit_template_subjects %></p>
</div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

esurvey/app/views/merit_templates/_merit_template_subject_fields.html.erb
<tr class="fields" >
<td>
<%= f.text_field :subject_name, class: "form-control" %>
</td>

<td>
<%= f.number_field :subject_marks, class: "form-control" %>
</td>


 <td ><%= link_to_remove_fields "<span class='glyphicon glyphicon-remove btn btn-sm '></span>".html_safe, f %>
 	</td>

  
</tr>

esurvey/app/views/merit_templates/edit.html.erb
<div class="page-header">
  <%= link_to merit_templates_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @merit_template, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h3 class="text-info"><u><b>Editing Merit Template and It's Subjects</b></u></h3>
  
</div>

<%= render 'form' %>

esurvey/app/views/merit_templates/index.html.erb
<div class="page-header">
  <%= link_to new_merit_template_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Merit template
  <% end %>

  <h3 class="text-info"><u><b>Listing Merit Templates</b></u></h3>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr class="bg-info">
         <th> S.No</th>
        <th>Template name</th>
        <th>No.of Subjects</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @merit_templates.each_with_index do |merit_template,index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= merit_template.template_name %></td>
            <th><%= merit_template.merit_template_subjects.length %></th>

            <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, merit_template ,:class=>"btn btn-sm btn-info"%></td>
            <td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_merit_template_path(merit_template),:class=>"btn btn-sm btn-success" %></td>
           <td><%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, merit_template,{ method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-sm btn-danger"  } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

esurvey/app/views/merit_templates/new.html.erb
<div class="page-header">
  <%= link_to merit_templates_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>

   <h3 class="text-info"><u><b>New Merit Template and It's Subjects</b></u></h3>
</div>

<%= render 'form' %>

esurvey/app/views/merit_templates/show.html.erb
<div class="page-header">
  <%= link_to merit_templates_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_merit_template_path(@merit_template), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h3 class="text-info"><u><b>Show Merit Template and It's Subjects</b></u></h3>
  
</div>

<dl class="dl-horizontal">
  <dt>Template name:</dt>
  <dd><%= @merit_template.template_name %></dd>

</dl>
 <div class="table-responsive">
 <table class="table table-bordered dynamic">
  <thead>
    <tr class="bg-info">
     <th>Subject Name </th>
     <th> Name Marks</th>
     <th>--</th>
  </tr>
  </thead>
   <tbody>
     <% @merit_template.merit_template_subjects.each_with_index do |merit_template_subject,index| %>
       <tr> 
         <td><%= merit_template_subject.subject_name %></td>
         <td><%= merit_template_subject.subject_marks %></td>
         <td><%= %> </td>
       </tr>
     <% end %>
  </tbody>
  </table>
</div>