esurvey/config/routes.rb
Esurvey::Application.routes.draw do
  resources :messages

  get "notifications/index"

  resources :merit_templates

  resources :interviews do
    collection do
     get 'get_survey_question'
     get 'get_servey_conducter'
     get 'get_survey_result'
     get 'get_survey_town'
     post 'calculate_survey_result'
     get 'calculate_survey_result_of_town'
    end
  end

  resources :survey_results

  resources :surveys do 
    collection do
      get 'listsurveyor'
      get 'add_surveyors'
      post 'update_surveyor'
    end
  end

  resources :political_parties  do 
   resources :users 
 end

match 'service/get_assigned_surveys/:user_id' => 'service#get_assigned_surveys'
match '/service/get_merit_list_of_survey/:surveys_id/:merit_template_id' =>'service#get_merit_list_of_survey'
match '/service/get_assigned_village_for_survey/:survey_id/:user_id'=>'service#get_assigned_village_for_survey'
match '/service/get_assigned_question_for_survey/:survey_id'=>'service#get_assigned_question_for_survey'
match '/service/get_interview_info/:interview_id'=>'service#get_interview_info' 

root :to => 'home#login_form'
 

   match ':controller(/:action(/:id))(.:format)'
end

esurvey/app/models/political_party.rb
class PoliticalParty < ActiveRecord::Base
  attr_accessible :description, :name,:picture_attributes,:is_active,:short_word
  
  validates :name,:presence=>true
  validates :name,uniqueness: { message: " should have unique Name",:case_sensitive => false },:if=>:name?
  validates :description,:presence=>true
  


  has_many :users;
  has_one :picture, :as => :imageable
  accepts_nested_attributes_for :picture
  




  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) }




end

esurvey/app/controllers/political_parties_controller.rb
class PoliticalPartiesController < ApplicationController
  # GET /political_parties
  # GET /political_parties.json
  filter_access_to :all
  def index
    @political_parties = PoliticalParty.all
    @active_political_parties = PoliticalParty.active
    @inactive_political_parties = PoliticalParty.inactive
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @political_parties }
    end
  end

  # GET /political_parties/1
  # GET /political_parties/1.json
  def show
    @political_party = PoliticalParty.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @political_party }
    end
  end

  # GET /political_parties/new
  # GET /political_parties/new.json
  def new
    @political_party = PoliticalParty.new
    @political_party.build_picture
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @political_party }
    end
  end

  # GET /political_parties/1/edit
  def edit
    @political_party = PoliticalParty.find(params[:id]) 
    @political_party.build_picture if @political_party.picture.nil?  
  end

  # POST /political_parties
  # POST /political_parties.json
  def create
    @political_party = PoliticalParty.new(params[:political_party])
    @political_party.build_picture if @political_party.picture.nil?
    respond_to do |format|
      if @political_party.save
        format.html { redirect_to @political_party, notice: 'Political party was successfully created.' }
        format.json { render json: @political_party, status: :created, location: @political_party }
      else
        format.html { render action: "new" }
        format.json { render json: @political_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /political_parties/1
  # PUT /political_parties/1.json
  def update
    @political_party = PoliticalParty.find(params[:id])
    @political_party.build_picture if @political_party.picture.nil?
    respond_to do |format|
      if @political_party.update_attributes(params[:political_party])
        format.html { redirect_to @political_party, notice: 'Political party was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @political_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /political_parties/1
  # DELETE /political_parties/1.json
  def destroy
    @political_party = PoliticalParty.find(params[:id])
    @political_party.update_attributes(:is_active=> !@political_party.is_active)
    respond_to do |format|
      format.html { redirect_to political_parties_url }
      format.json { head :no_content }
    end
  end

end

esurvey/app/helpers/political_parties_helper.rb
module PoliticalPartiesHelper
end

esurvey/app/views/political_parties/_form.html.erb
<%= form_for(@political_party, html: { class: "form-horizontal", role: "form",:multipart => true }) do |f| %>
  <% if @political_party.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@political_party.errors.count, "error") %> prohibited this political_party from being saved:</h4>

      <ul>
      <% @political_party.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :short_word, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :short_word, class: "form-control" %>
    </div>
  </div> 
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :cols=>"10",:rows=>"5",class: "form-control" %>
    </div>
  </div>

<%= f.fields_for :picture do |picture| %>
<div class="form-group">
  <label class="col-sm-2 control-label" for="filebutton">Upload Party Image</label>
  <div class="col-sm-3">
      <%= picture.file_field :picture %>
     </div>
</div>
<% end %>

<% unless @political_party.new_record? %>
 <%  unless @political_party.picture.nil? %>
  <div class="form-group">
  <label class="col-sm-2 control-label" for="filebutton">Earlier logo</label>
     <div class="col-sm-3">
      <%= image_tag @political_party.picture.picture.url(:thumb)   %>
     </div>
   </div>  

<% end %>
<% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
    
  </div>
<% end %>

esurvey/app/views/political_parties/edit.html.erb
<div class="page-header">
  <%= link_to political_parties_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @political_party, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <%= link_to new_political_party_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Political party
  <% end %>
  <h3 class="text-info"><u><b> Editing  <%= @political_party.name %> Details</b></u></h3>
</div>

<%= render 'form' %>

esurvey/app/views/political_parties/index.html.erb
<div class="page-header">
  <%= link_to new_political_party_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Political party
  <% end %>
  <h3 class="text-info"><u><b>Active Political Party List </b></u></h3>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr> 
            <th>S.No</th>
             <th>Party Logo</th>
             <th>Short Name</th>
            <th>Full Name</th>
            <th>Description</th>
           
            <th>show</th>
            <th>Edit</th>
            <th>Deactivate</th>
            <th>Explore</th>
        
      </tr>
    </thead>

    <tbody>
      <% @active_political_parties.each_with_index do |political_party,index| %>
         <tr>
            <td><%= index+1 %></td>
            <td><%= image_tag political_party.picture.picture.url(:thumb) unless political_party.picture.nil?  %></td>
            <td><%= political_party.short_word %></td>
            <td><%= political_party.name %></td>
            <td><%= political_party.description[0..30]+"..." %></td>
            
            <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, political_party ,:class=>"btn btn-sm btn-info"%></td>
        <td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_political_party_path(political_party),:class=>"btn btn-sm btn-success" %></td>
        <td><%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, political_party, {method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-sm btn-danger" } %></td>
        <td><%= link_to '<i class="fa fa-user" aria-hidden="true"></i>'.html_safe,political_party_users_url(political_party),:class=>"btn btn-sm btn-info" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>



<div class="page-header">
 
  <h3 class="text-info"><u><b>In Active Political Party List </b></u></h3>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>  <th>S.No</th>
              <th>Party Logo</th>
             <th>Short Name</th>
            <th>Full Name</th>
            <th>Description</th>
           
            <th>show</th>
            <th>Edit</th>
            <th>Deactivate</th>
        
      </tr>
    </thead>

    <tbody>
      <% @inactive_political_parties.each_with_index do |political_party,index| %>
         <tr>
            <td><%= index+1 %></td>
             <td><%= image_tag political_party.picture.picture.url(:thumb) unless political_party.picture.nil?  %></td>
            <td><%= political_party.short_word %></td>
            <td><%= political_party.name %></td>
            <td><%= political_party.description[0..30]+"..." %></td>
           
            <td><%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, political_party ,:class=>"btn btn-sm btn-info"%></td>
        <td><%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_political_party_path(political_party),:class=>"btn btn-sm btn-success" %></td>
        <td><%= link_to '<i class="fa fa-times" aria-hidden="true"></i>'.html_safe, political_party, {method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-sm btn-danger" } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

esurvey/app/views/political_parties/new.html.erb
<div class="page-header">
  <%= link_to political_parties_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to new_political_party_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Political party
  <% end %>
  <h3 class="text-info"><u><b>New political_party</b></u></h3>
</div>

<%= render 'form' %>

esurvey/app/views/political_parties/show.html.erb
<div class="page-header">
  <%= link_to political_parties_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_political_party_path(@political_party), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <%= link_to new_political_party_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Political party
  <% end %>
  <h3 class="text-info"><u><b><%= @political_party.name %> Details</b></u></h3>
</div>

<dl class="dl-horizontal">
   <dt class="text-justify text-danger">Logo:</dt>
   <dd class="text-justify"><%= image_tag @political_party.picture.picture.url(:thumb) unless @political_party.picture.nil?  %></dd>
  <dt class="text-justify text-danger">Name:</dt>
  <dd class="text-justify"><%= @political_party.name %></dd>

  <dt class="text-justify text-danger">Description:</dt>
  <dd class="text-justify"><%= @political_party.description %></dd>

</dl>